### ISSUE TITLE
Make the timer integratable as an iframe

### ISSUE THREAD

**Issue by LeonGeldsch** [Districtfine/20-20-20#6]
It would be nice if only the timer by itself could be integratable as an iframe to use as a widget on a custom startpage.
If you like this idea but lack of time I would be happy to provide the pull request myself!

**Comment by Districtfine** [comment]
Go ahead I'd welcome a PR. I'm not much of a web developer and haven't touched this project in a while. So I'd be happy to merge your changes

**Comment by LaputanMachines** [comment]
I'd love to see that too -- that way it can be integrated into other people's web apps more seamlessly. @Districtfine does this project have an Open Source-y license that allows it to be leveraged by others?

**Comment by LeonGeldsch** [comment]
Integration into external sites is now possible! 🥳
